ci:
  autofix_prs: true
  autofix_commit_msg: '[pre-commit.ci] auto fixes'
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore(deps): pre-commit autoupdate'

repos:
- repo: https://github.com/pre-commit/pre-commit
  rev: v3.8.0
  hooks:
  - id: validate_manifest

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-json
    exclude: "\\.vscode/.*.json"
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.7
  hooks:
  - id: ruff
  - id: ruff-format
